{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "scraper-secrets",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "scraper-secrets",
        "namespace": "default",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "POSTGRES_PASSWORD": "AgBUeW0i507LI8gtSr6yKPR7dwB6aeYTutER6ToW7XNjLIeUYHK5oWSeOwGRjdH2JIM2DzCE3qinuMw0axQUUupEAa/bxl4aCEU4KQIsR6hrNuB6WK2XBaJRKYuicqC6t9myXQk8KjlkDKze4rqBgx+MpiYsRooEbete3Ll/XUiFLbIV8Yb79aGP4bPx/AFx9+Oq1JVAorCnFuMKDR0wJ3GCRHBMlDChJ9Yjm90oil4/R0EsxQCbDDVQj4ir0gea0Tgn9jgLc6c9TCHLldtpPxU1HIfDnQ9ULNrVHr6u/bgUnkEtGkVavIAAuEUH1FkAZuEOJdAPHuNs4iXRhMqNttxgWd/jbkubycyPgcy60pW6aF1T8k3U8Uhd2lNkiEh9G7G2RJwJEkZ/VHOKY4UPVSaTzNbTRpsh4swXxKXfXEZ7YLacOaZwVF8Nnjy3YsveHTCM7tJ3FWHQzvnJtbFKvk7FfObx4gqt0CezGrR/mi9Egiac0vffYMD+P6y0TyVFFjzxGDabTOHeAqB0/3mJKAxqFQZRD6lSVCCOq0SCsFApaBnlDfDgn/Ov0RIkshAHfqGZMDoO0nvySL49vsgTGZMwxsAD9nNmJDs4ULugeYV9aDm5/nL7JXw97Nhd4EOC25PoA9zrx1ShlqHFuigAfamJihh0CmH24LKRRzpYGvk1YIYL+V91tWuMWd7M3ukrVv1Upji/jw+ixkqLtqNYJH14"
    }
  },
  "status": {
    
  }
}
