services:
  product-service:
    hostname: product-service
    depends_on:
      product-db:
        condition: service_started
    build: ./src/product-service
    ports:
      - "8080:8080"
  scraper-service:
    depends_on:
      scraper-db:
        condition: service_started
    build: ./src/scraper-service
    ports:
      - "8001:8001"
  product-db:
    hostname: product-db
    image: mongo
    ports:
      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#      MONGO_INITDB_DATABASE: products
    volumes:
      - ./src/product-service/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodbdata:/data/db
  wait-for-mongo:
      image: docker.io/busybox:1.35
      depends_on:
        product-db:
          condition: service_healthy
      command: sh -c "until nc -z product-db 27017; do echo 'Waiting for MongoDB'; sleep 2; done"
  scraper-db:
    hostname: scraper-db
    image: postgres
    restart: always
    ports:
      - "8082:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgresqldata:/var/lib/postgresql/data/
  ui:
    build: ./src/ui
    ports:
      - "3000:3000"
volumes:
  mongodbdata:
    driver: local
  postgresqldata:
    driver: local
  
