services:
  product-service:
    build: ./src/product-service
    ports:
      - "8081:8080"
  scraper-service:
    depends_on:
      scraper_db:
        condition: service_started
    build: ./src/scraper-service
    ports:
      - "8001:8001"
  scraper_db:
    hostname: scraper_db
    image: postgres
    restart: always
    ports:
      - "8082:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
