apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: product-service:dev
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "512m"
          limits:
            memory: "2048Mi"
            cpu: "2"
        env:
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secrets
                key: DB_PASSWORD
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              configMapKeyRef:
                name: product-configmap
                key: PRODUCTS_USER
          - name: SPRING_JPA_HIBERNATE_DDL-AUTO
            valueFrom:
              configMapKeyRef:
                name: database-configmap
                key: DDL-AUTO
        envFrom:
          - configMapRef:
              name: app-config
          - configMapRef:
              name: product-configmap
