apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: auth-service:dev
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 10 
          periodSeconds: 5        
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            memory: "512Mi"
            cpu: "512m"
          limits:
            memory: "1024Mi"
            cpu: "1"
        env:
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: JWT_SECRET_KEY
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secrets
                key: DB_PASSWORD
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              configMapKeyRef:
                name: auth-configmap
                key: AUTH_USER
          - name: CORS_ALLOWED_ORIGINS
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: cors.allowed.origins
        envFrom:
          - configMapRef:
              name: app-config
          - configMapRef:
              name: auth-configmap