apiVersion: v1
kind: Service
metadata:
  name: scraper-service
spec:
  selector:
    app: scraper-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper-service
  template:
    metadata:
      labels:
        app: scraper-service
    spec:
      containers:
      - name: scraper-service
        image: scraper-service:dev
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1024m"
          limits:
            memory: "4096Mi"
            cpu: "4096m"
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secrets
                key: DB_PASSWORD
        envFrom:
          - configMapRef:
              name: app-config
          - configMapRef:
              name: database-configmap
          - configMapRef:
              name: scraper-configmap
