{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "auth-secrets",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "auth-secrets",
        "namespace": "default",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "JWT_SECRET_KEY": "AgB1aazQXYRIpgYzx4uXB4gim+PIMFMZ7s+P4p5UIsOADjZwa69zAKRZxmNEz1cPmTyEa77cj1HguvB2+hUO3KFylyO5Sptx4IadLYryGIyt/Q8qsTQPh2XSSt0F391GFmI9zCKPRRDrF2CuTpsga5DL+mWXvvqWEt5NplC2fuAv6Z8n3gCiKbq5IRHa3MN8LZJZ1+a+uLb6jRLkB2FIaFQlnZeItLJpKOMTKeJoQqm0TbhzhXjVpQ4F6j2LUu0jzfh4NTgl8ixwzNoKbCWVCzfkl7VtzBgNUqqrjgpX4f7Xc/5OIBc6qUDJapcXOqsBGRJJSErf7B14dxG9nNPWZckVu3SGqJ6B3g99pigvVnV5aX0UlwWRUSc5/9TlBP0qlddEW9ZsasTwbDezVvOBcCHWOhDe0pG6WZCjeuakmSYISjPQnxdjpzdbD/ztay3Fr3XCrB05qnORR/cMlLK7zLoDmOIqnbtJonCKE9Q651uxr8tjGuI/DDXM6c/8ozHTMSS7qFSp5FXMM15qjhPkvOl/yP32KBrSCHDlhMwaA13T38X4aiBw+6FMELUHlltA/yGYAEyxTfYMEFXAo0nnoSL+AE6Cr+qeIv9NVsp6fEvBFsk9yWMZP8bMWa74R+SXMXwyuwiSKa8X+qEbGzOO7Be+Qw3w7lGXb9oWTrP0+10XhnyPBQjivzYFJdxA5LMkZEG7ske/5vP+vXmDDV9g62wTsmyRvXVwFWkUrU6PmazBKxbPGFEQjJD/QGpZ5tW1rCeotN+D85sUnZ9nmNFI7rWnAeZsXrbxh+nLsM2Vo1uD3w==",
    }
  },
  "status": {
    
  }
}
