apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: postgres
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1"     # Max 1 CPU core
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: DB_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: database-configmap
              key: DB_USER
        envFrom:
          - configMapRef:
              name: auth-configmap
          - configMapRef:
              name: product-configmap
          - configMapRef:
              name: scraper-configmap
        volumeMounts:
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d/init.sh
          subPath: init.sh
        - name: databasedata1
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: init-script
        configMap:
          name: init-db-script
          defaultMode: 0777
      - name: databasedata1
        persistentVolumeClaim:
          claimName: databasedata1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: databasedata1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi