apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-secrets
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgCRXOkooK4bHBNcN5+WY3lP38qO1IoZ60X2JQtMAuQ1x9ZGZwcvrRqkF65xVV5Uus8dRV525egMYNaokkqxxD/GBDVKzdP9TAp6jyftMBTQN7iDh1AVR7Gx+j5m3ngF/3OR14/jvvH4zKvZ8Fu0ax7AzJ34z5PbnQfb8r+VDlSh0+M+8x0+61X/UCOs078hKrrXE/znO4/ydYj0+ogPR0wVvDJfSMSsJQ1hs7Gbwq638G6sLheAOv/iCfeXGr20072n8/zGNJ9bqEcPf2DBBQ4rQLUaVvgfK956D/VfoKpfE5pM18EzDwUJWVSOagRaUqmGfjzcww5cisExDF8HeVjslfmfClVriMvVuMAoqc4EW2DMsDMlG8+If1rCsEnpiuFoaT7XPnwgOdGfZwfVlKpUaoEWFuSSStFLBIleax4wa3YhBsDSvne6Jnlfy8i7OllIIjjo6TA1LD69HnakiDGE/SKSaXVq4bBC5lYj5pqoRkpfAKPl20HrSt0r1LSUQ45LQyHANtIMHlvv31bPlbkISIMdxTPOTORP2X0LJquvc/ZBz4yZm+HkKLh/ecUpZNK0yw5XMy1mmpEv/9EXElGGLIwq4IPbFOgkgxrX4h5uO0JxPBzB2D6kUhN7OGb5ios+0y25HwltOWfoEQBX6FutSTezCtnsOXtXD/zNNbs0r5hthGuM6R6wKERwh8am5s8MDZG16Exe5iL7A/ApKWkPU7SlGZcf30pY2oMkB/Mr5SiM
  template:
    metadata:
      creationTimestamp: null
      name: database-secrets
      namespace: default
status: {}

