resources:
  - ../../base
  - secrets/auth-secrets-sealed.yaml
  - secrets/database-secrets-sealed.yaml
  - database/database.yaml
  - database/init-db-script.yaml

configMapGenerator:
- name: app-config
  behavior: merge
  literals:
  - ui.host=dev.ui.local
  - cors.allowed.origins=http://dev.ui.local

patches:
  - path: product-service-patch/product-service-replica-patch.yaml
    target:
      kind: Deployment
      name: product-service
  - path: ui-patch/ui-replica-patch.yaml
    target:
      kind: Deployment
      name: ui
  - path: scraper-service-patch/scraper-service-replica-patch.yaml
    target:
      kind: Deployment
      name: scraper-service
  - path: configmap-patch/app-config-patch.yaml
    target:
      kind: ConfigMap
      name: app-config
  - path: auth-service-patch/auth-configmap-patch.yaml
    target:
      kind: ConfigMap
      name: auth-configmap
  - path: product-service-patch/product-configmap-patch.yaml
    target:
      kind: ConfigMap
      name: product-configmap
  - path: database/database-configmap-patch.yaml
    target:
      kind: ConfigMap
      name: database-configmap
  - target:
      kind: Ingress
      name: protected-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: dev.ui.local
  - target:
      kind: Ingress
      name: ui-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: dev.ui.local
