resources:
  - ../../base
  - auth-secrets-sealed.yaml
  - database-secrets-sealed.yaml
  - database.yaml
  - init-db-script.yaml

patches:
  - path: product-service-replica-patch.yaml
    target:
      kind: Deployment
      name: product-service
  - path: ui-replica-patch.yaml
    target:
      kind: Deployment
      name: ui
  - path: scraper-service-replica-patch.yaml
    target:
      kind: Deployment
      name: scraper-service
  - path: app-config-patch.yaml
    target:
      kind: ConfigMap
      name: app-config
  - path: auth-configmap-patch.yaml
    target:
      kind: ConfigMap
      name: auth-configmap
  - path: product-configmap-patch.yaml
    target:
      kind: ConfigMap
      name: product-configmap
  - path: database-configmap-patch.yaml
    target:
      kind: ConfigMap
      name: database-configmap
