name: Auth Service Tests

on:
  push:
    branches:
      - 'feature/**'
      - 'develop'
    paths:
      - 'src/auth-service/**'
  pull_request:
    branches:
      - develop
    paths:
      - 'src/auth-service/**'

jobs:
  test-auth-service:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      # Step 3: Run mvnw verify
      - name: Run mvnw verify
        working-directory: src/auth-service
        run: |
          chmod +x mvnw
          ./mvnw verify
