name: Product Service Tests

on:
  push:
    branches:
      - 'feature/**'
    paths:
      - 'src/product-service/**' # Trigger only when files in src/product-service are changed
  pull_request:
    branches:
      - develop
    paths:
      - 'src/product-service/**' # Trigger only when files in src/product-service are changed

jobs:
  test-product-service:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      # Step 3: Run mvnw verify
      - name: Run mvnw verify
        working-directory: src/product-service
        run: |
          chmod +x mvnw
          ./mvnw verify
